extern pin_obj_t pin_PA0 ;
extern pin_obj_t pin_PA1 ;
extern pin_obj_t pin_PA2 ;
extern pin_obj_t pin_PA3 ;
extern pin_obj_t pin_PA4 ;
extern pin_obj_t pin_PA5 ;
extern pin_obj_t pin_PA6 ;
extern pin_obj_t pin_PA7 ;
extern pin_obj_t pin_PA8 ;
extern pin_obj_t pin_PA9 ;
extern pin_obj_t pin_PA10;
extern pin_obj_t pin_PA11;
extern pin_obj_t pin_PA12;
extern pin_obj_t pin_PB0 ;
extern pin_obj_t pin_PB1 ;
extern pin_obj_t pin_PB2 ;
extern pin_obj_t pin_PB3 ;
extern pin_obj_t pin_PB4 ;
extern pin_obj_t pin_PB5 ;
extern pin_obj_t pin_PB6 ;
extern pin_obj_t pin_PB7 ;
extern pin_obj_t pin_PB8 ;
extern pin_obj_t pin_PB9 ;
extern pin_obj_t pin_PB10;
extern pin_obj_t pin_PB11;
extern pin_obj_t pin_PB12;
extern pin_obj_t pin_PC0 ;
extern pin_obj_t pin_PC1 ;
extern pin_obj_t pin_PC2 ;
extern pin_obj_t pin_PC3 ;
extern pin_obj_t pin_PC4 ;
extern pin_obj_t pin_PC5 ;
extern pin_obj_t pin_PC6 ;
extern pin_obj_t pin_PC7 ;
