extern const pin_af_t pin_PA0_af[];
extern pin_obj_t pin_PA0 ;
extern const pin_af_t pin_PA1_af[];
extern pin_obj_t pin_PA1 ;
extern const pin_af_t pin_PA2_af[];
extern pin_obj_t pin_PA2 ;
extern const pin_af_t pin_PA3_af[];
extern pin_obj_t pin_PA3 ;
extern const pin_af_t pin_PA4_af[];
extern pin_obj_t pin_PA4 ;
extern const pin_af_t pin_PA5_af[];
extern pin_obj_t pin_PA5 ;
extern const pin_af_t pin_PA6_af[];
extern pin_obj_t pin_PA6 ;
extern const pin_af_t pin_PA7_af[];
extern pin_obj_t pin_PA7 ;
extern const pin_af_t pin_PA8_af[];
extern pin_obj_t pin_PA8 ;
extern const pin_af_t pin_PA9_af[];
extern pin_obj_t pin_PA9 ;
extern const pin_af_t pin_PA10_af[];
extern pin_obj_t pin_PA10;
extern const pin_af_t pin_PA11_af[];
extern pin_obj_t pin_PA11;
extern const pin_af_t pin_PA12_af[];
extern pin_obj_t pin_PA12;
extern const pin_af_t pin_PA13_af[];
extern pin_obj_t pin_PA13;
extern const pin_af_t pin_PA14_af[];
extern pin_obj_t pin_PA14;
extern const pin_af_t pin_PA15_af[];
extern pin_obj_t pin_PA15;
extern const pin_af_t pin_PB0_af[];
extern pin_obj_t pin_PB0 ;
extern const pin_af_t pin_PB1_af[];
extern pin_obj_t pin_PB1 ;
extern const pin_af_t pin_PB2_af[];
extern pin_obj_t pin_PB2 ;
extern const pin_af_t pin_PB3_af[];
extern pin_obj_t pin_PB3 ;
extern const pin_af_t pin_PB4_af[];
extern pin_obj_t pin_PB4 ;
extern const pin_af_t pin_PB5_af[];
extern pin_obj_t pin_PB5 ;
extern const pin_af_t pin_PB6_af[];
extern pin_obj_t pin_PB6 ;
extern const pin_af_t pin_PB7_af[];
extern pin_obj_t pin_PB7 ;
extern const pin_af_t pin_PB8_af[];
extern pin_obj_t pin_PB8 ;
extern const pin_af_t pin_PB9_af[];
extern pin_obj_t pin_PB9 ;
extern const pin_af_t pin_PB10_af[];
extern pin_obj_t pin_PB10;
extern const pin_af_t pin_PB11_af[];
extern pin_obj_t pin_PB11;
extern const pin_af_t pin_PB12_af[];
extern pin_obj_t pin_PB12;
extern const pin_af_t pin_PB13_af[];
extern pin_obj_t pin_PB13;
extern const pin_af_t pin_PB14_af[];
extern pin_obj_t pin_PB14;
extern const pin_af_t pin_PB15_af[];
extern pin_obj_t pin_PB15;
extern const pin_af_t pin_PC0_af[];
extern pin_obj_t pin_PC0 ;
extern const pin_af_t pin_PC1_af[];
extern pin_obj_t pin_PC1 ;
extern const pin_af_t pin_PC2_af[];
extern pin_obj_t pin_PC2 ;
extern const pin_af_t pin_PC3_af[];
extern pin_obj_t pin_PC3 ;
extern const pin_af_t pin_PC4_af[];
extern pin_obj_t pin_PC4 ;
extern const pin_af_t pin_PC5_af[];
extern pin_obj_t pin_PC5 ;
extern const pin_af_t pin_PC6_af[];
extern pin_obj_t pin_PC6 ;
extern const pin_af_t pin_PC7_af[];
extern pin_obj_t pin_PC7 ;
extern const pin_af_t pin_PC8_af[];
extern pin_obj_t pin_PC8 ;
extern const pin_af_t pin_PC9_af[];
extern pin_obj_t pin_PC9 ;
extern const pin_af_t pin_PC10_af[];
extern pin_obj_t pin_PC10;
extern const pin_af_t pin_PC11_af[];
extern pin_obj_t pin_PC11;
extern const pin_af_t pin_PC12_af[];
extern pin_obj_t pin_PC12;
extern const pin_af_t pin_PC13_af[];
extern pin_obj_t pin_PC13;
extern const pin_af_t pin_PC14_af[];
extern pin_obj_t pin_PC14;
extern const pin_af_t pin_PD0_af[];
extern pin_obj_t pin_PD0 ;
extern const pin_af_t pin_PD1_af[];
extern pin_obj_t pin_PD1 ;
extern const pin_af_t pin_PD2_af[];
extern pin_obj_t pin_PD2 ;
extern const pin_af_t pin_PD3_af[];
extern pin_obj_t pin_PD3 ;
extern const pin_af_t pin_PD4_af[];
extern pin_obj_t pin_PD4 ;
extern const pin_af_t pin_PD5_af[];
extern pin_obj_t pin_PD5 ;
extern const pin_af_t pin_PD6_af[];
extern pin_obj_t pin_PD6 ;
extern const pin_af_t pin_PD7_af[];
extern pin_obj_t pin_PD7 ;
extern const pin_af_t pin_PD8_af[];
extern pin_obj_t pin_PD8 ;
extern const pin_af_t pin_PD9_af[];
extern pin_obj_t pin_PD9 ;
extern const pin_af_t pin_PD10_af[];
extern pin_obj_t pin_PD10;
extern const pin_af_t pin_PD11_af[];
extern pin_obj_t pin_PD11;
extern const pin_af_t pin_PD12_af[];
extern pin_obj_t pin_PD12;
extern const pin_af_t pin_PD13_af[];
extern pin_obj_t pin_PD13;
extern const pin_af_t pin_PD14_af[];
extern pin_obj_t pin_PD14;
extern const pin_af_t pin_PE0_af[];
extern pin_obj_t pin_PE0 ;
extern const pin_af_t pin_PE1_af[];
extern pin_obj_t pin_PE1 ;
extern const pin_af_t pin_PE2_af[];
extern pin_obj_t pin_PE2 ;
extern const pin_af_t pin_PE3_af[];
extern pin_obj_t pin_PE3 ;
extern const pin_af_t pin_PE4_af[];
extern pin_obj_t pin_PE4 ;
extern const pin_af_t pin_PE5_af[];
extern pin_obj_t pin_PE5 ;
extern const pin_af_t pin_PE6_af[];
extern pin_obj_t pin_PE6 ;
extern const pin_af_t pin_PE7_af[];
extern pin_obj_t pin_PE7 ;
extern const pin_af_t pin_PE8_af[];
extern pin_obj_t pin_PE8 ;
extern const pin_af_t pin_PE9_af[];
extern pin_obj_t pin_PE9 ;
extern const pin_af_t pin_PE10_af[];
extern pin_obj_t pin_PE10;
extern const pin_af_t pin_PE11_af[];
extern pin_obj_t pin_PE11;
extern const pin_af_t pin_PE12_af[];
extern pin_obj_t pin_PE12;
extern const pin_af_t pin_PE13_af[];
extern pin_obj_t pin_PE13;
extern const pin_af_t pin_PE14_af[];
extern pin_obj_t pin_PE14;
extern const pin_af_t pin_PE15_af[];
extern pin_obj_t pin_PE15;
extern const pin_af_t pin_PF0_af[];
extern pin_obj_t pin_PF0 ;
extern const pin_af_t pin_PF1_af[];
extern pin_obj_t pin_PF1 ;
extern const pin_af_t pin_PF2_af[];
extern pin_obj_t pin_PF2 ;
extern const pin_af_t pin_PF3_af[];
extern pin_obj_t pin_PF3 ;
extern const pin_af_t pin_PF4_af[];
extern pin_obj_t pin_PF4 ;
extern const pin_af_t pin_PF5_af[];
extern pin_obj_t pin_PF5 ;
extern const pin_af_t pin_PF6_af[];
extern pin_obj_t pin_PF6 ;
extern const pin_af_t pin_PF7_af[];
extern pin_obj_t pin_PF7 ;
extern const pin_af_t pin_PF8_af[];
extern pin_obj_t pin_PF8 ;
extern const pin_af_t pin_PF9_af[];
extern pin_obj_t pin_PF9 ;
extern const pin_af_t pin_PF10_af[];
extern pin_obj_t pin_PF10;
extern const pin_af_t pin_PF11_af[];
extern pin_obj_t pin_PF11;
extern const pin_af_t pin_PG0_af[];
extern pin_obj_t pin_PG0 ;
extern const pin_af_t pin_PG1_af[];
extern pin_obj_t pin_PG1 ;
extern const pin_af_t pin_PG2_af[];
extern pin_obj_t pin_PG2 ;
extern const pin_af_t pin_PG3_af[];
extern pin_obj_t pin_PG3 ;
extern const pin_af_t pin_PG4_af[];
extern pin_obj_t pin_PG4 ;
extern const pin_af_t pin_PG5_af[];
extern pin_obj_t pin_PG5 ;
extern const pin_af_t pin_PG6_af[];
extern pin_obj_t pin_PG6 ;
extern const pin_af_t pin_PG7_af[];
extern pin_obj_t pin_PG7 ;
extern const pin_af_t pin_PG8_af[];
extern pin_obj_t pin_PG8 ;
extern const pin_af_t pin_PG9_af[];
extern pin_obj_t pin_PG9 ;
extern const pin_af_t pin_PG10_af[];
extern pin_obj_t pin_PG10;
extern const pin_af_t pin_PG11_af[];
extern pin_obj_t pin_PG11;
extern const pin_af_t pin_PG12_af[];
extern pin_obj_t pin_PG12;
extern const pin_af_t pin_PG13_af[];
extern pin_obj_t pin_PG13;
extern const pin_af_t pin_PG14_af[];
extern pin_obj_t pin_PG14;
extern const pin_af_t pin_PG15_af[];
extern pin_obj_t pin_PG15;
extern const pin_af_t pin_PH0_af[];
extern pin_obj_t pin_PH0 ;
extern const pin_af_t pin_PH1_af[];
extern pin_obj_t pin_PH1 ;
extern const pin_af_t pin_PH2_af[];
extern pin_obj_t pin_PH2 ;
extern const pin_af_t pin_PH3_af[];
extern pin_obj_t pin_PH3 ;
extern const pin_af_t pin_PH4_af[];
extern pin_obj_t pin_PH4 ;
extern const pin_af_t pin_PH5_af[];
extern pin_obj_t pin_PH5 ;
extern const pin_af_t pin_PH6_af[];
extern pin_obj_t pin_PH6 ;
extern const pin_af_t pin_PH7_af[];
extern pin_obj_t pin_PH7 ;
extern const pin_af_t pin_PH8_af[];
extern pin_obj_t pin_PH8 ;
extern const pin_af_t pin_PH9_af[];
extern pin_obj_t pin_PH9 ;
extern const pin_af_t pin_PH10_af[];
extern pin_obj_t pin_PH10;
extern const pin_af_t pin_PH11_af[];
extern pin_obj_t pin_PH11;
