// This file was automatically generated by make-pins.py
//
// --prefix boards/W600_prefix.c

/*
 * This file is part of the MicroPython project, http://micropython.org/
 *
 * The MIT License (MIT)
 *
 * Copyright (c) 2013, 2014 Damien P. George
 * Copyright (c) 2015 Daniel Campora
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

// W600_prefix.c becomes the initial portion of the generated pins file.

#include <stdio.h>
#include <stdint.h>

#include "py/mpconfig.h"
#include "py/obj.h"
#include "pybpin.h"
#include "wm_type_def.h"
#include "wm_regs.h"
#include "wm_io.h"


#define PIN(_name, _index) \
{ \
    { &pin_type }, \
    .name        = MP_QSTR_ ## _name, \
    .index       = (_index), \
    .alt         = 5, \
    .dir         = 0, \
    .mode        = 0, \
    .value       = 0, \
    .irq_trigger = 0, \
    .irq_flags   = 0, \
}

pin_obj_t pin_PA0  = PIN(PA0 , WM_IO_PA_00);
pin_obj_t pin_PA1  = PIN(PA1 , WM_IO_PA_01);
pin_obj_t pin_PA4  = PIN(PA4 , WM_IO_PA_04);
pin_obj_t pin_PA5  = PIN(PA5 , WM_IO_PA_05);
pin_obj_t pin_PB6  = PIN(PB6 , WM_IO_PB_06);
pin_obj_t pin_PB7  = PIN(PB7 , WM_IO_PB_07);
pin_obj_t pin_PB8  = PIN(PB8 , WM_IO_PB_08);
pin_obj_t pin_PB9  = PIN(PB9 , WM_IO_PB_09);
pin_obj_t pin_PB10 = PIN(PB10, WM_IO_PB_10);
pin_obj_t pin_PB11 = PIN(PB11, WM_IO_PB_11);
pin_obj_t pin_PB12 = PIN(PB12, WM_IO_PB_12);
pin_obj_t pin_PB13 = PIN(PB13, WM_IO_PB_13);
pin_obj_t pin_PB14 = PIN(PB14, WM_IO_PB_14);
pin_obj_t pin_PB15 = PIN(PB15, WM_IO_PB_15);
pin_obj_t pin_PB16 = PIN(PB16, WM_IO_PB_16);
pin_obj_t pin_PB17 = PIN(PB17, WM_IO_PB_17);
pin_obj_t pin_PB18 = PIN(PB18, WM_IO_PB_18);

STATIC const mp_rom_map_elem_t pins_locals_dict_table[] = {
    { MP_ROM_QSTR(MP_QSTR_PA0 ),  MP_ROM_PTR(&pin_PA0 ) },
    { MP_ROM_QSTR(MP_QSTR_PA1 ),  MP_ROM_PTR(&pin_PA1 ) },
    { MP_ROM_QSTR(MP_QSTR_PA4 ),  MP_ROM_PTR(&pin_PA4 ) },
    { MP_ROM_QSTR(MP_QSTR_PA5 ),  MP_ROM_PTR(&pin_PA5 ) },
    { MP_ROM_QSTR(MP_QSTR_PB6 ),  MP_ROM_PTR(&pin_PB6 ) },
    { MP_ROM_QSTR(MP_QSTR_PB7 ),  MP_ROM_PTR(&pin_PB7 ) },
    { MP_ROM_QSTR(MP_QSTR_PB8 ),  MP_ROM_PTR(&pin_PB8 ) },
    { MP_ROM_QSTR(MP_QSTR_PB9 ),  MP_ROM_PTR(&pin_PB9 ) },
    { MP_ROM_QSTR(MP_QSTR_PB10),  MP_ROM_PTR(&pin_PB10) },
    { MP_ROM_QSTR(MP_QSTR_PB11),  MP_ROM_PTR(&pin_PB11) },
    { MP_ROM_QSTR(MP_QSTR_PB12),  MP_ROM_PTR(&pin_PB12) },
    { MP_ROM_QSTR(MP_QSTR_PB13),  MP_ROM_PTR(&pin_PB13) },
    { MP_ROM_QSTR(MP_QSTR_PB14),  MP_ROM_PTR(&pin_PB14) },
    { MP_ROM_QSTR(MP_QSTR_PB15),  MP_ROM_PTR(&pin_PB15) },
    { MP_ROM_QSTR(MP_QSTR_PB16),  MP_ROM_PTR(&pin_PB16) },
    { MP_ROM_QSTR(MP_QSTR_PB17),  MP_ROM_PTR(&pin_PB17) },
    { MP_ROM_QSTR(MP_QSTR_PB18),  MP_ROM_PTR(&pin_PB18) },
};

MP_DEFINE_CONST_DICT(pins_locals_dict, pins_locals_dict_table);
