extern pin_obj_t pin_PA0 ;
extern pin_obj_t pin_PA1 ;
extern pin_obj_t pin_PA4 ;
extern pin_obj_t pin_PA5 ;
extern pin_obj_t pin_PB6 ;
extern pin_obj_t pin_PB7 ;
extern pin_obj_t pin_PB8 ;
extern pin_obj_t pin_PB9 ;
extern pin_obj_t pin_PB10;
extern pin_obj_t pin_PB11;
extern pin_obj_t pin_PB12;
extern pin_obj_t pin_PB13;
extern pin_obj_t pin_PB14;
extern pin_obj_t pin_PB15;
extern pin_obj_t pin_PB16;
extern pin_obj_t pin_PB17;
extern pin_obj_t pin_PB18;
