// This file was automatically generated by make-pins.py
//
// --af chip/SWM320_port.h
// --prefix boards/SWM320_prefix.c

/*
 * This file is part of the MicroPython project, http://micropython.org/
 *
 * The MIT License (MIT)
 *
 * Copyright (c) 2013, 2014 Damien P. George
 * Copyright (c) 2015 Daniel Campora
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

// SWM320_prefix.c becomes the initial portion of the generated pins file.

#include <stdio.h>
#include <stdint.h>

#include "py/mpconfig.h"
#include "py/obj.h"

#include "pybpin.h"


#define PIN(_name, _port, _pbit) \
{ \
    { &pin_type }, \
    .name        = MP_QSTR_ ## _name, \
    .port        = (_port), \
    .pbit        = (_pbit), \
    .alt         = 0, \
    .dir         = 0, \
    .mode        = 0, \
    .priority    = 0, \
    .callback    = 0, \
}


pin_obj_t pin_PA0  = PIN(PA0 , GPIOA, PIN0);

pin_obj_t pin_PA1  = PIN(PA1 , GPIOA, PIN1);

pin_obj_t pin_PA2  = PIN(PA2 , GPIOA, PIN2);

pin_obj_t pin_PA3  = PIN(PA3 , GPIOA, PIN3);

pin_obj_t pin_PA4  = PIN(PA4 , GPIOA, PIN4);

pin_obj_t pin_PA5  = PIN(PA5 , GPIOA, PIN5);

pin_obj_t pin_PA6  = PIN(PA6 , GPIOA, PIN6);

pin_obj_t pin_PA7  = PIN(PA7 , GPIOA, PIN7);

pin_obj_t pin_PA8  = PIN(PA8 , GPIOA, PIN8);

pin_obj_t pin_PA9  = PIN(PA9 , GPIOA, PIN9);

pin_obj_t pin_PA10 = PIN(PA10, GPIOA, PIN10);

pin_obj_t pin_PA11 = PIN(PA11, GPIOA, PIN11);

pin_obj_t pin_PA12 = PIN(PA12, GPIOA, PIN12);

pin_obj_t pin_PB0  = PIN(PB0 , GPIOB, PIN0);

pin_obj_t pin_PB1  = PIN(PB1 , GPIOB, PIN1);

pin_obj_t pin_PB2  = PIN(PB2 , GPIOB, PIN2);

pin_obj_t pin_PB3  = PIN(PB3 , GPIOB, PIN3);

pin_obj_t pin_PB4  = PIN(PB4 , GPIOB, PIN4);

pin_obj_t pin_PB5  = PIN(PB5 , GPIOB, PIN5);

pin_obj_t pin_PB6  = PIN(PB6 , GPIOB, PIN6);

pin_obj_t pin_PB7  = PIN(PB7 , GPIOB, PIN7);

pin_obj_t pin_PB8  = PIN(PB8 , GPIOB, PIN8);

pin_obj_t pin_PB9  = PIN(PB9 , GPIOB, PIN9);

pin_obj_t pin_PB10 = PIN(PB10, GPIOB, PIN10);

pin_obj_t pin_PB11 = PIN(PB11, GPIOB, PIN11);

pin_obj_t pin_PB12 = PIN(PB12, GPIOB, PIN12);

pin_obj_t pin_PC0  = PIN(PC0 , GPIOC, PIN0);

pin_obj_t pin_PC1  = PIN(PC1 , GPIOC, PIN1);

pin_obj_t pin_PC2  = PIN(PC2 , GPIOC, PIN2);

pin_obj_t pin_PC3  = PIN(PC3 , GPIOC, PIN3);

pin_obj_t pin_PC4  = PIN(PC4 , GPIOC, PIN4);

pin_obj_t pin_PC5  = PIN(PC5 , GPIOC, PIN5);

pin_obj_t pin_PC6  = PIN(PC6 , GPIOC, PIN6);

pin_obj_t pin_PC7  = PIN(PC7 , GPIOC, PIN7);


STATIC const mp_rom_map_elem_t pins_locals_dict_table[] = {
    { MP_ROM_QSTR(MP_QSTR_PA0  ),  MP_ROM_PTR(&pin_PA0  ) },
    { MP_ROM_QSTR(MP_QSTR_PA1  ),  MP_ROM_PTR(&pin_PA1  ) },
    { MP_ROM_QSTR(MP_QSTR_PA2  ),  MP_ROM_PTR(&pin_PA2  ) },
    { MP_ROM_QSTR(MP_QSTR_PA3  ),  MP_ROM_PTR(&pin_PA3  ) },
    { MP_ROM_QSTR(MP_QSTR_PA4  ),  MP_ROM_PTR(&pin_PA4  ) },
    { MP_ROM_QSTR(MP_QSTR_PA5  ),  MP_ROM_PTR(&pin_PA5  ) },
    { MP_ROM_QSTR(MP_QSTR_PA6  ),  MP_ROM_PTR(&pin_PA6  ) },
    { MP_ROM_QSTR(MP_QSTR_PA7  ),  MP_ROM_PTR(&pin_PA7  ) },
    { MP_ROM_QSTR(MP_QSTR_PA8  ),  MP_ROM_PTR(&pin_PA8  ) },
    { MP_ROM_QSTR(MP_QSTR_PA9  ),  MP_ROM_PTR(&pin_PA9  ) },
    { MP_ROM_QSTR(MP_QSTR_PA10 ),  MP_ROM_PTR(&pin_PA10 ) },
    { MP_ROM_QSTR(MP_QSTR_PA11 ),  MP_ROM_PTR(&pin_PA11 ) },
    { MP_ROM_QSTR(MP_QSTR_PA12 ),  MP_ROM_PTR(&pin_PA12 ) },
    { MP_ROM_QSTR(MP_QSTR_PB0  ),  MP_ROM_PTR(&pin_PB0  ) },
    { MP_ROM_QSTR(MP_QSTR_PB1  ),  MP_ROM_PTR(&pin_PB1  ) },
    { MP_ROM_QSTR(MP_QSTR_PB2  ),  MP_ROM_PTR(&pin_PB2  ) },
    { MP_ROM_QSTR(MP_QSTR_PB3  ),  MP_ROM_PTR(&pin_PB3  ) },
    { MP_ROM_QSTR(MP_QSTR_PB4  ),  MP_ROM_PTR(&pin_PB4  ) },
    { MP_ROM_QSTR(MP_QSTR_PB5  ),  MP_ROM_PTR(&pin_PB5  ) },
    { MP_ROM_QSTR(MP_QSTR_PB6  ),  MP_ROM_PTR(&pin_PB6  ) },
    { MP_ROM_QSTR(MP_QSTR_PB7  ),  MP_ROM_PTR(&pin_PB7  ) },
    { MP_ROM_QSTR(MP_QSTR_PB8  ),  MP_ROM_PTR(&pin_PB8  ) },
    { MP_ROM_QSTR(MP_QSTR_PB9  ),  MP_ROM_PTR(&pin_PB9  ) },
    { MP_ROM_QSTR(MP_QSTR_PB10 ),  MP_ROM_PTR(&pin_PB10 ) },
    { MP_ROM_QSTR(MP_QSTR_PB11 ),  MP_ROM_PTR(&pin_PB11 ) },
    { MP_ROM_QSTR(MP_QSTR_PB12 ),  MP_ROM_PTR(&pin_PB12 ) },
    { MP_ROM_QSTR(MP_QSTR_PC0  ),  MP_ROM_PTR(&pin_PC0  ) },
    { MP_ROM_QSTR(MP_QSTR_PC1  ),  MP_ROM_PTR(&pin_PC1  ) },
    { MP_ROM_QSTR(MP_QSTR_PC2  ),  MP_ROM_PTR(&pin_PC2  ) },
    { MP_ROM_QSTR(MP_QSTR_PC3  ),  MP_ROM_PTR(&pin_PC3  ) },
    { MP_ROM_QSTR(MP_QSTR_PC4  ),  MP_ROM_PTR(&pin_PC4  ) },
    { MP_ROM_QSTR(MP_QSTR_PC5  ),  MP_ROM_PTR(&pin_PC5  ) },
    { MP_ROM_QSTR(MP_QSTR_PC6  ),  MP_ROM_PTR(&pin_PC6  ) },
    { MP_ROM_QSTR(MP_QSTR_PC7  ),  MP_ROM_PTR(&pin_PC7  ) },
};

MP_DEFINE_CONST_DICT(pins_locals_dict, pins_locals_dict_table);
