// This file was generated by py/makeversionhdr.py
#define MICROPY_GIT_TAG "v1.9.4-484-ga3cfabc-dirty"
#define MICROPY_GIT_HASH "a3cfabc-dirty"
#define MICROPY_BUILD_DATE "2018-08-31"
#define MICROPY_VERSION_MAJOR (1)
#define MICROPY_VERSION_MINOR (9)
#define MICROPY_VERSION_MICRO (4)
#define MICROPY_VERSION_STRING "1.9.4"
