extern pin_obj_t pin_GPIO0 ;
extern pin_obj_t pin_GPIO1 ;
extern pin_obj_t pin_GPIO2 ;
extern pin_obj_t pin_GPIO3 ;
extern pin_obj_t pin_GPIO4 ;
extern pin_obj_t pin_GPIO5 ;
extern pin_obj_t pin_GPIO6 ;
extern pin_obj_t pin_GPIO7 ;
extern pin_obj_t pin_GPIO24;
extern pin_obj_t pin_GPIO25;
extern pin_obj_t pin_GPIO26;
extern pin_obj_t pin_GPIO27;
extern pin_obj_t pin_GPIO28;
extern pin_obj_t pin_GPIO29;
extern pin_obj_t pin_GPIO30;
extern pin_obj_t pin_GPIO31;
extern pin_obj_t pin_GPIO32;
extern pin_obj_t pin_GPIO33;
extern pin_obj_t pin_GPIO34;
extern pin_obj_t pin_GPIO35;
extern pin_obj_t pin_GPIO36;
extern pin_obj_t pin_GPIO37;
extern pin_obj_t pin_GPIO38;
extern pin_obj_t pin_GPIO39;
extern pin_obj_t pin_GPIO57;
extern pin_obj_t pin_GPIO58;
extern pin_obj_t pin_GPIO59;
extern pin_obj_t pin_GPIO60;
