// This file was automatically generated by make-pins.py
//
// --af chip/Include/MT7687_GPIO.h
// --prefix boards/MT7687_prefix.c

/*
 * This file is part of the MicroPython project, http://micropython.org/
 *
 * The MIT License (MIT)
 *
 * Copyright (c) 2013, 2014 Damien P. George
 * Copyright (c) 2015 Daniel Campora
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

// MT7687_prefix.c becomes the initial portion of the generated pins file.

#include <stdio.h>
#include <stdint.h>

#include "py/mpconfig.h"
#include "py/obj.h"
#include "pybpin.h"
#include "MT7687.h"


#define PIN(_name, _index) \
{ \
    { &pyb_pin_type }, \
    .name        = MP_QSTR_ ## _name, \
    .index       = (_index), \
    .alt         = 0, \
    .dir         = 0, \
    .mode        = 0, \
    .value       = 0, \
    .irq_trigger = 0, \
    .irq_flags   = 0, \
}

pin_obj_t pin_GPIO0  = PIN(GPIO0 , 0 );

pin_obj_t pin_GPIO1  = PIN(GPIO1 , 1 );

pin_obj_t pin_GPIO2  = PIN(GPIO2 , 2 );

pin_obj_t pin_GPIO3  = PIN(GPIO3 , 3 );

pin_obj_t pin_GPIO4  = PIN(GPIO4 , 4 );

pin_obj_t pin_GPIO5  = PIN(GPIO5 , 5 );

pin_obj_t pin_GPIO6  = PIN(GPIO6 , 6 );

pin_obj_t pin_GPIO7  = PIN(GPIO7 , 7 );

pin_obj_t pin_GPIO24 = PIN(GPIO24, 24);

pin_obj_t pin_GPIO25 = PIN(GPIO25, 25);

pin_obj_t pin_GPIO26 = PIN(GPIO26, 26);

pin_obj_t pin_GPIO27 = PIN(GPIO27, 27);

pin_obj_t pin_GPIO28 = PIN(GPIO28, 28);

pin_obj_t pin_GPIO29 = PIN(GPIO29, 29);

pin_obj_t pin_GPIO30 = PIN(GPIO30, 30);

pin_obj_t pin_GPIO31 = PIN(GPIO31, 31);

pin_obj_t pin_GPIO32 = PIN(GPIO32, 32);

pin_obj_t pin_GPIO33 = PIN(GPIO33, 33);

pin_obj_t pin_GPIO34 = PIN(GPIO34, 34);

pin_obj_t pin_GPIO35 = PIN(GPIO35, 35);

pin_obj_t pin_GPIO36 = PIN(GPIO36, 36);

pin_obj_t pin_GPIO37 = PIN(GPIO37, 37);

pin_obj_t pin_GPIO38 = PIN(GPIO38, 38);

pin_obj_t pin_GPIO39 = PIN(GPIO39, 39);

pin_obj_t pin_GPIO57 = PIN(GPIO57, 57);

pin_obj_t pin_GPIO58 = PIN(GPIO58, 58);

pin_obj_t pin_GPIO59 = PIN(GPIO59, 59);

pin_obj_t pin_GPIO60 = PIN(GPIO60, 60);


STATIC const mp_rom_map_elem_t pins_locals_dict_table[] = {
    { MP_ROM_QSTR(MP_QSTR_GPIO0  ),  MP_ROM_PTR(&pin_GPIO0  ) },
    { MP_ROM_QSTR(MP_QSTR_GPIO1  ),  MP_ROM_PTR(&pin_GPIO1  ) },
    { MP_ROM_QSTR(MP_QSTR_GPIO2  ),  MP_ROM_PTR(&pin_GPIO2  ) },
    { MP_ROM_QSTR(MP_QSTR_GPIO3  ),  MP_ROM_PTR(&pin_GPIO3  ) },
    { MP_ROM_QSTR(MP_QSTR_GPIO4  ),  MP_ROM_PTR(&pin_GPIO4  ) },
    { MP_ROM_QSTR(MP_QSTR_GPIO5  ),  MP_ROM_PTR(&pin_GPIO5  ) },
    { MP_ROM_QSTR(MP_QSTR_GPIO6  ),  MP_ROM_PTR(&pin_GPIO6  ) },
    { MP_ROM_QSTR(MP_QSTR_GPIO7  ),  MP_ROM_PTR(&pin_GPIO7  ) },
    { MP_ROM_QSTR(MP_QSTR_GPIO24 ),  MP_ROM_PTR(&pin_GPIO24 ) },
    { MP_ROM_QSTR(MP_QSTR_GPIO25 ),  MP_ROM_PTR(&pin_GPIO25 ) },
    { MP_ROM_QSTR(MP_QSTR_GPIO26 ),  MP_ROM_PTR(&pin_GPIO26 ) },
    { MP_ROM_QSTR(MP_QSTR_GPIO27 ),  MP_ROM_PTR(&pin_GPIO27 ) },
    { MP_ROM_QSTR(MP_QSTR_GPIO28 ),  MP_ROM_PTR(&pin_GPIO28 ) },
    { MP_ROM_QSTR(MP_QSTR_GPIO29 ),  MP_ROM_PTR(&pin_GPIO29 ) },
    { MP_ROM_QSTR(MP_QSTR_GPIO30 ),  MP_ROM_PTR(&pin_GPIO30 ) },
    { MP_ROM_QSTR(MP_QSTR_GPIO31 ),  MP_ROM_PTR(&pin_GPIO31 ) },
    { MP_ROM_QSTR(MP_QSTR_GPIO32 ),  MP_ROM_PTR(&pin_GPIO32 ) },
    { MP_ROM_QSTR(MP_QSTR_GPIO33 ),  MP_ROM_PTR(&pin_GPIO33 ) },
    { MP_ROM_QSTR(MP_QSTR_GPIO34 ),  MP_ROM_PTR(&pin_GPIO34 ) },
    { MP_ROM_QSTR(MP_QSTR_GPIO35 ),  MP_ROM_PTR(&pin_GPIO35 ) },
    { MP_ROM_QSTR(MP_QSTR_GPIO36 ),  MP_ROM_PTR(&pin_GPIO36 ) },
    { MP_ROM_QSTR(MP_QSTR_GPIO37 ),  MP_ROM_PTR(&pin_GPIO37 ) },
    { MP_ROM_QSTR(MP_QSTR_GPIO38 ),  MP_ROM_PTR(&pin_GPIO38 ) },
    { MP_ROM_QSTR(MP_QSTR_GPIO39 ),  MP_ROM_PTR(&pin_GPIO39 ) },
    { MP_ROM_QSTR(MP_QSTR_GPIO57 ),  MP_ROM_PTR(&pin_GPIO57 ) },
    { MP_ROM_QSTR(MP_QSTR_GPIO58 ),  MP_ROM_PTR(&pin_GPIO58 ) },
    { MP_ROM_QSTR(MP_QSTR_GPIO59 ),  MP_ROM_PTR(&pin_GPIO59 ) },
    { MP_ROM_QSTR(MP_QSTR_GPIO60 ),  MP_ROM_PTR(&pin_GPIO60 ) },
};

MP_DEFINE_CONST_DICT(pins_locals_dict, pins_locals_dict_table);
